### ISSUE TITLE
Unable to push branch because the branch is behind the deployed branch. Using --force to deploy branch. 

### ISSUE THREAD

**Issue by celsoMartins** [AkhileshNS/heroku-deploy#35]
Hi. First of all, thanks for your work. It is becoming an easy-going and straightforward tool to use inside the actions.

But for two days I'm getting this error in my deploy action. The branches in Heroku are pretty clean and I can use it normally in my local environment, pushing to Heroku. It also works in the Travis CI.

Don't mind the open Postgres user and pass. It will be changed and moved to secrets and my test database has no secrets to the outside world.

Pay attention, please, on the "staging deploy" since the "production deploy" has some attempts I've made within these two days.

What am I missing?

I'll appreciate any help.

Thanks

Config file:

```
name: FlowClimateBuild
on: [push]

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.1
      - name: Ruby gem cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Run linters
        run: |
          bundle exec rubocop --parallel

  tests:
    name: Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: flowcontrol_test
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "postgres"
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.1
      - name: Ruby gem cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Setup test database
        env:
          RAILS_ENV: test
          PG_HOST: localhost
          PG_USER: ""
          PG_PASSWORD: ""
          PG_PORT: ${{ job.services.postgres.ports['5432'] }}
        run: |
          bundle exec rails db:setup

      - name: Run tests
        run: bundle exec rspec
        env:
          secret_key_32_encoded: "8L+WeHTWhNtEAvQzoRaYqYtl4VCwDMReh2SzicO/iCA=\n"

  deploy-staging:
    runs-on: ubuntu-latest
    #    needs: [linters, tests]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: akhileshns/heroku-deploy@v3.5.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "flowclimatestaging"
          heroku_email: "celso.av.martins@gmail.com"

  deploy-prd:
    runs-on: ubuntu-latest
    #    needs: [linters, tests]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Staging deploy
        run: |
          git push -f https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/flowclimateapp.git origin/develop:master

```

Complete error message:

```
Created and wrote to ~/.netrc
Successfully logged into heroku
heroku: Press any key to open up the browser to login or q to exit:  ›   Warning: heroku update available from 7.43.0 to 7.43.2.
Added git remote heroku
heroku: Press any key to open up the browser to login or q to exit: fatal: 'heroku' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

            Unable to push branch because the branch is behind the deployed branch. Using --force to deploy branch. 
            (If you want to avoid this, set dontuseforce to 1 in with: of .github/workflows/action.yml. 
            Specifically, the error was: Error: Command failed: git push heroku HEAD:refs/heads/master 
fatal: 'heroku' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

        
fatal: 'heroku' does not appear to be a git repository
Error: Error: Command failed: git push heroku HEAD:refs/heads/master --force
fatal: 'heroku' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by akashkj** [comment]
I am also facing similar issue during push

**Comment by BlueGhostGH** [comment]
I am also facing this issue

**Comment by AkhileshNS** [comment]
Hey guys sorry for replying late. I'm not entirely sure what the cause of the issue is here but as a start, I would recommend adding this line

```yaml
- run: git config user.email "USER EMAIL" && git config user.name "USER NAME" && git add -A && git commit -m "Updated code"
```

to your action steps (and specifically place it just before the action step). This seems to have solved similar issues for people in the past (which is why I'm considering just making it a part of the action) and lemme know if that helps

Also if possible, could you provide with more of the logs you've received from the action. It would be helpful in diagnosing the issue

**Comment by celsoMartins** [comment]
Thanks, @AkhileshNS.

I already put the complete log I've received.

I'm not comfortable to commit code in the action, because it may cause several and serious sync problems.

I'll try to reset any changes in the action, instead of commit. What do you think?

In a few hours, I'll have a push to try it.

**Comment by AkhileshNS** [comment]
Keep in mind that any commits that you do in the actions environment won't reflect on the repo itself until you push them to your "origin" remote. So whatever commits you do in the actions environment will simply disappear once the actions have completed executing. Since they're temporary commits, they're relatively safe. 

Although any commits you do in the actions environment will be pushed to the "heroku" remote (since that's how Heroku actually deploys your code). It creates a git repository and adds a remote to that repository under the moniker of "heroku". Then just runs `git push heroku master`. That's also why if you're making any changes to your application in the actions environment before deploying them, those changes won't show up, since Heroku is using Git and git will only deploy the latest commits. 

So all this leads me to believe that committing code in the action shouldn't cause any sync problems if that's all you're doing. Even if some sync issues show up in the "heroku" remote, the action will force push them (since it prioritizes deploying whatever the current form of the application is).

But resetting changes isn't a bad idea either. I'm not entirely sure what's causing the issue on your end so feel free to try this and see if it helps. I'll try and do whatever I can on my end based on the logs provided

**Comment by celsoMartins** [comment]
> Keep in mind that any commits that you do in the actions environment won't reflect on the repo itself until you push them to your "origin" remote. So whatever commits you do in the actions environment will simply disappear once the actions have completed executing. Since they're temporary commits, they're relatively safe.

Yes, I know. =)
> 
> Although any commits you do in the actions environment will be pushed to the "heroku" remote (since that's how Heroku actually deploys your code). It creates a git repository and adds a remote to that repository under the moniker of "heroku". Then just runs `git push heroku master`. That's also why if you're making any changes to your application in the actions environment before deploying them, those changes won't show up, since Heroku is using Git and git will only deploy the latest commits.

Yes, but it will require a force push from the developers' local environment directly to Heroku in order to keep everything synced. We try to keep everything up to date.
> 
> So all this leads me to believe that committing code in the action shouldn't cause any sync problems if that's all you're doing. Even if some sync issues show up in the "heroku" remote, the action will force push them (since it prioritizes deploying whatever the current form of the application is).
> 
> But resetting changes isn't a bad idea either. I'm not entirely sure what's causing the issue on your end so feel free to try this and see if it helps. I'll try and do whatever I can on my end based on the logs provided

Thank you so much for your effort. I am going to push an attempt now.

**Comment by celsoMartins** [comment]
So, are you proposing something like this?

```
    deploy-staging:
    runs-on: ubuntu-latest
    needs: [linters, tests]
    
    if: github.ref == 'refs/heads/develop'
    steps:
      - run: |
          git add .
          git reset --hard HEAD
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.5.6
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "flowclimatestaging"
          heroku_email: "celso.av.martins@gmail.com"
```

**Comment by celsoMartins** [comment]
It was not recognized as a git repo.

```
Run git add .
  git add .
  git reset --hard HEAD
  shell: /bin/bash -e {0}
fatal: not a git repository (or any of the parent directories): .git
Error: Process completed with exit code 128.
```

**Comment by AkhileshNS** [comment]
You've ran the git reset commands before the checkout action which clones the git repo. So it's not detecting it. 

Additionally, I don't think resetting changes will matter since based on the logs, I don't think Heroku was even able to login, Can you double check that you have set the HEROKU_API_KEY secret

**Comment by celsoMartins** [comment]
Yes, you were right. And the message states that Heroku is in front of the Github branch, and it is not true. Nobody here pushes directly to Heroku and I turn off the deployment in Travis every time I run a test here.

I have the API key set and I regenerated and updated it during my tests.

https://jmp.sh/8yvUaio

In the beginning, I tested exhaustively the sync with the Heroku repo and I have no problems with my local environment and in Travis as well.

It is an open-source repository and you can check some configurations on yourself if you need to.

https://github.com/TallerWebSolutions/flow_climate

**Comment by AkhileshNS** [comment]
Hey sorry for the late update, but I think your problem might be happening because the app name you're using (flowclimatestaging) is already taken (unless you're the one who took it). So try changing the app name to something else and see if that works

**Comment by celsoMartins** [comment]
> Hey sorry for the late update, but I think your problem might be happening because the app name you're using (flowclimatestaging) is already taken (unless you're the one who took it). So try changing the app name to something else and see if that works

No problem.

The app name is ours. =)

**Comment by MagdyYoussef** [comment]
i just tried the action today .. and i've been struggling with it for hours now .. here's the log file if it would help:

`Run AkhileshNS/heroku-deploy@v3.5.7
  with:
    heroku_api_key: ***
    heroku_app_name: ***
    heroku_email: ***
    dontuseforce: false
    usedocker: false
    docker_heroku_process_type: web
    delay: 0
    rollbackonhealthcheckfailed: false
From https://github.com/***/***
 * [new branch]      create-deployment-workflow -> origin/create-deployment-workflow
 * [new branch]      remove-env-file     -> origin/remove-env-file
Created and wrote to ~/.netrc
 * [new branch]      test-deployment     -> origin/test-deployment
 * [new branch]      test-github-actions -> origin/test-github-actions
 ›   Warning: Our terms of service have changed: 
 ›   https://dashboard.heroku.com/terms-of-service
Successfully logged into heroku
heroku: Press any key to open up the browser to login or q to exit:  ›   Warning: heroku update available from 7.44.0 to 7.45.0.
Added git remote heroku
remote: 
remote: !	Push rejected, cannot delete master branch        
remote: 
To https://git.heroku.com/***.git
 ! [remote rejected] master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/***.git'

            Unable to push branch because the branch is behind the deployed branch. Using --force to deploy branch. 
            (If you want to avoid this, set dontuseforce to 1 in with: of .github/workflows/action.yml. 
            Specifically, the error was: Error: Command failed: git push heroku :refs/heads/master 
remote: 
remote: !	Push rejected, cannot delete master branch        
remote: 
To https://git.heroku.com/***.git
 ! [remote rejected] master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/***.git'

        
remote: 
remote: !	Push rejected, cannot delete master branch        
remote: 
To https://git.heroku.com/***.git
 ! [remote rejected] master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/***.git'
Error: Error: Command failed: git push heroku :refs/heads/master --force
remote: 
remote: !	Push rejected, cannot delete master branch        
remote: 
To https://git.heroku.com/***.git
 ! [remote rejected] master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/***.git'`

and your proposed solution just didn't work:

> Run git config user.email "***" && git config user.name "****" && git add -A && git commit -m "Updated code"
  git config user.email "***" && git config user.name "*****" && git add -A && git commit -m "Updated code"
  shell: /bin/bash -e {0}
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
Error: Process completed with exit code 1.

>

**Comment by AkhileshNS** [comment]
Hey @celsoMartins, sorry again for the late response. I've added a feature to Action where now you can just login to Heroku and run your own heroku cli commands. Since I expect that whatever is causing your issue is likely to do with Action running these commands from within it's own environment. Hopefully running within Github actions itself should help you.

Check [https://github.com/AkhileshNS/heroku-deploy#just-login](https://github.com/AkhileshNS/heroku-deploy#just-login) for more info. And let me know if this resolves your issue

**Comment by rogargon** [comment]
Not working for me either, in my case deploying using Docker:

```
  deploy:
    if: ${{ github.event_name == 'push' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "my-app-name"
          heroku_email: "my@email.com"
          usedocker: true
```

The output complaints about git pushing to Heroku. My understanding is that deploying to Heroku using Docker doesn't 
require git, so very confusing.

```
Run akhileshns/heroku-deploy@v3.6.8
Created and wrote to ~/.netrc
 ›   Warning: Our terms of service have changed: 
 ›   https://dashboard.heroku.com/terms-of-service
heroku: Press any key to open up the browser to login or q to exit:  ›   Warning: heroku update available from 7.46.0 to 7.46.2.
WARNING! Your password will be stored unencrypted in /home/runner/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Successfully logged into heroku
 ›   Warning: heroku update available from 7.46.0 to 7.46.2.
Added git remote heroku
 ›   Warning: heroku update available from 7.46.0 to 7.46.2.
ADD failed: no source files were specified
 ▸    Error: docker build exited with Error: 1

            Unable to push branch because the branch is behind the deployed branch. Using --force to deploy branch. 
            (If you want to avoid this, set dontuseforce to 1 in with: of .github/workflows/action.yml. 
            Specifically, the error was: Error: Command failed: heroku container:push web --app my-app-name 
 ›   Warning: heroku update available from 7.46.0 to 7.46.2.
ADD failed: no source files were specified
 ▸    Error: docker build exited with Error: 1

        
 ›   Warning: heroku update available from 7.46.0 to 7.46.2.
ADD failed: no source files were specified
 ▸    Error: docker build exited with Error: 1
Error: Error: Command failed: heroku container:push web --app my-app-name 
 ›   Warning: heroku update available from 7.46.0 to 7.46.2.
ADD failed: no source files were specified
 ▸    Error: docker build exited with Error: 1
```

**Comment by AkhileshNS** [comment]
So some of the git logs are just default logs from the action (I suppose that needs to be updated). 

Based on your logs @rogargon, it seems like there might be a path issue with the ADD command in Docker. So the two fixes that come to mind are, you can try switching from ADD to COPY (which works sometimes somehow) or you could doublecheck if the path to whatever you're importing is accurate relative to the location of the Dockerfile.

Sources:
[https://stackoverflow.com/questions/47281687/dockerfile-add-failed-no-source-files-were-specified](https://stackoverflow.com/questions/47281687/dockerfile-add-failed-no-source-files-were-specified)
[https://stackoverflow.com/questions/54425742/docker-add-giving-error-no-source-files-were-specified](https://stackoverflow.com/questions/54425742/docker-add-giving-error-no-source-files-were-specified)

If it's none of these and the problem is in fact an issue with the Action, then you can try the following:
```yaml
name: Deploy

on:
  push:
    branches:
      - master # Changing the branch here would also work

jobs:
  deploy:
    if: ${{ github.event_name == 'push' }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.6.8 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "" 
          heroku_email: "YOUR EMAIL"
          justlogin: true
      - run: |
          heroku container:login
          # Run commands you would typically run from the heroku cli on your local machine to deploy your code
```
The "justlogin" option essentially turns the "heroku-deploy" action to a "heroku-login" action for all intents and purposes. So from there you should be able to use it like you would use the local Cli on your machine to deploy your code. So based on that, I would recommend deploying the code you have on your machine from the heroku cli and add the same commands in the comments section and it should just work.

**Comment by AkhileshNS** [comment]
Closing this issue due to inactivity. Please feel free to reopen this issue if it is still relevant to you

**Comment by celsoMartins** [comment]
I really don't know what happened but I put my original setup and it is working now.

Thank you! By Travis!

**Comment by mattpodolak** [comment]
Hi, I have also encountered this issue:
```
Run akhileshns/heroku-deploy@v3.7.8
Created and wrote to ~/.netrc
 ›   Warning: Our terms of service have changed: 
 ›   https://dashboard.heroku.com/terms-of-service
heroku: Press any key to open up the browser to login or q to exit:  ›   Warning: heroku update available from 7.47.3 to 7.47.5.
Successfully logged into heroku
WARNING! Your password will be stored unencrypted in /home/runner/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

 ›   Warning: heroku update available from 7.47.3 to 7.47.5.
Added git remote heroku
 ›   Warning: heroku update available from 7.47.3 to 7.47.5.
Setting NODE_ENV, USER, PASS and restarting ***... done, v3
 ›   Warning: heroku update available from 7.47.3 to 7.47.5.
The command '/bin/sh -c npm run build' returned a non-zero code: 1
 ▸    Error: docker build exited with Error: 1

            Unable to push branch because the branch is behind the deployed branch. Using --force to deploy branch. 
            (If you want to avoid this, set dontuseforce to 1 in with: of .github/workflows/action.yml. 
            Specifically, the error was: Error: Command failed: heroku container:push web --app *** 
 ›   Warning: heroku update available from 7.47.3 to 7.47.5.
The command '/bin/sh -c npm run build' returned a non-zero code: 1
 ▸    Error: docker build exited with Error: 1

        
 ›   Warning: heroku update available from 7.47.3 to 7.47.5.
The command '/bin/sh -c npm run build' returned a non-zero code: 1
 ▸    Error: docker build exited with Error: 1
Error: Error: Command failed: heroku container:push web --app *** 
 ›   Warning: heroku update available from 7.47.3 to 7.47.5.
The command '/bin/sh -c npm run build' returned a non-zero code: 1
 ▸    Error: docker build exited with Error: 1
```

The app was freshly created manually on Heroku and has 0 commits, the name used in use by me. I have attached my GitHub Action code below as well:
```
name: Deploy to Heroku Staging Environment

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.7.8
        with:
          branch: master
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_STG_APP }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          healthcheck: ${{ secrets.STG_APP_URL }}
          delay: 10
          usedocker: true
        env:
          HD_NODE_ENV: production
          HD_USER: ${{ secrets.USER }}
          HD_PASS: ${{ secrets.PASS }}
```

**Comment by AkhileshNS** [comment]
Hey @mattpodolak, your workflow file looks fine for the most part (though I would remove `branch: master` since the Action's default of `branch: HEAD` is going to work just fine). Based on the logs, whatever issue seems to stem from this line specifically

```
The command '/bin/sh -c npm run build' returned a non-zero code: 1
```

JavaScript and NPM will by default return code 1 (which just means "failure") if something goes wrong. But that could be referring to just about any error so it doesn't really give you a lot of info. From what I can tell though, it says that `npm run build` is not working for some reason. It could be you're using this inside the Dockerfile and maybe you missed a `npm install` somewhere. It would be a little more helpful if you could share your Dockerfile (if that's alright) or alternatively you can view the row logs of the run and see if there's any useful info there

You can find raw logs by opening one of the runs of your github actions and clicking the gear icon on the top right

![Row Logs location](https://user-images.githubusercontent.com/21128574/102296595-afe8f180-3f73-11eb-8042-310486d47860.png)

**Comment by AkhileshNS** [comment]
> 
> 
> I really don't know what happened but I put my original setup and it is working now.
> 
> Thank you! Bye Travis!

Great to hear @celsoMartins. Sorry if I wasn't much help

**Comment by dfalling** [comment]
I'd love to understand how people fixed this.  This broke for me as well:

```yaml
name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@master
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
```

Error:
<details>
<summary>
Error message
</summary>

```

Created and wrote to ~/.netrc
 ›   Warning: Our terms of service have changed: 
Successfully logged into heroku
 ›   dashboard.heroku.com/terms-of-service
heroku: Press any key to open up the browser to login or q to exit:  ›   Warning: heroku update available from 7.47.4 to 7.47.6.
Added git remote heroku
heroku: Press any key to open up the browser to login or q to exit: fatal: 'heroku' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

            Unable to push branch because the branch is behind the deployed branch. Using --force to deploy branch. 
            (If you want to avoid this, set dontuseforce to 1 in with: of .github/workflows/action.yml. 
            Specifically, the error was: Error: Command failed: git push heroku HEAD:refs/heads/master 
fatal: 'heroku' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

        
fatal: 'heroku' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: Error: Command failed: git push heroku HEAD:refs/heads/master --force
fatal: 'heroku' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
</details>

**Comment by AkhileshNS** [comment]
Hey @dfalling, could you confirm once if your App Name isn't already taken?

**Comment by dfalling** [comment]
> Hey @dfalling, could you confirm once if your App Name isn't already taken?

Hey @AkhileshNS thanks for the quick response!  Yes, my app name isn't already taken.  This workflow was working great until about two months when it started failing (Mon, 12 Oct 2020).

**Comment by AkhileshNS** [comment]
Based on what research I could do (checkout this [link](https://stackoverflow.com/questions/22657578/git-push-heroku-could-not-read-from-remote-repository) on StackOverflow), some people have suggested that this might be an error with the git remote not being set correctly:

So for now, could you try this and see if it helps:

```yaml
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@master
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          justlogin: true
      - run: |
          # git config user.name "<NAME>" && git config user.email "<EMAIL>" # You may have to do this as well
          git remote add heroku git@heroku.com:<HEROKU_APP_NAME>.git
          git push heroku master
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
```

Lemme know if any of this helps

**Comment by dfalling** [comment]
I tried those commands (including the commented out one) before the Heroku action, which failed because I'm not logged into Heroku at that point.

When I try them afterwards, using `if: always()` to force it to run despite the failing Heroku job, it fails with
```
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I ran a `git remote -v` before this as well, which revealed only the `origin` remote, so it looks like the commands inside the Heroku action were failing?

Is it possible the error is from the earlier messages?
```
Created and wrote to ~/.netrc
 ›   Warning: Our terms of service have changed: 
Successfully logged into heroku
 ›   dashboard.heroku.com/terms-of-service
heroku: Press any key to open up the browser to login or q to exit:  ›   Warning: heroku update available from 7.47.4 to 7.47.6.
Added git remote heroku
heroku: Press any key to open up the browser to login or q to exit: fatal: 'heroku' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I have three other projects using this action successfully so I'm at a loss as to why this one started failing.

**Comment by AkhileshNS** [comment]
It looks like it's expecting some sort of ssh key sharing which is odd since it never asks for this in other cases (and heroku should allow for deployments via ci/cd after all). Since Heroku makes it deployments via git, this might be an issue with the remote repository connecting to your heroku deploy repo as opposed to something specific to Heroku. I'll try to see if I can come up with a fix for it by the end of the day

But for the moment, if it's possible, can you try removing the heroku app inside heroku.com and re-deploying it. Hopefully that might fix it.

**Comment by dfalling** [comment]
I tried removing the app and redeploying which failed for invalid ID (no app).  Then I recreated and pushed and hit the same error.

**Comment by AkhileshNS** [comment]
hey @dfalling, sorry for the late reply. I haven't honestly been able to figure out what the problem seems to be with your deployment. For now the only thing I can recommend is maybe changing the name of your heroku app and trying to deploy again (or maybe moving to a new repository and trying as well) if any of these options are available to you. 

I do plan on shifting Heroku Deploy's default deployment method from the Heroku Cli to [dpl](https://github.com/travis-ci/dpl) which is the deployment tool used by Travis, and dpl deploys to Heroku using the Heroku API instead of Git (Although a git option is also available). Hopefully this might help fix your issue

**Comment by dfalling** [comment]
No worries!  The problem does feel like it's with Heroku / Heroku CLI, not this action.  I'll see if I can figure anything out on their end and report back if I get it working.

`dpl`'s a great tool, I suspect that would solve this as well.

**Comment by dfalling** [comment]
@AkhileshNS My problem ended up being an expired access token.  I'm not sure why the errors didn't point towards this at all, but on a whim I tried a fresh token and pushes worked again. 🤷‍♂️  Thanks for the help!

**Comment by AkhileshNS** [comment]
The App definitely needs better logging and maybe even a checklist if common issues.

But good to hear your issue is resolved

**Comment by dfalling** [comment]
Actually when I was troubleshooting this I used the Heroku CLI directly and its warnings weren't any help.  Ideally it would give me some sort of feedback to let me know my auth was failing, but the errors pointed other ways every time.

**Comment by AkhileshNS** [comment]
Maybe it's worth writing some custom tests then. The kind that checks for the app name being available, if the OAuth token is working or not, and stuff like that, and then prints more appropriate error messages (The sort you wouldn't get if you just used the heroku cli). Although adding these tests might make the application slower so it's worth testing these things first

**Comment by huong-dang** [comment]
@AkhileshNS Hi there, I've been encountering "Host Key verification failed" error when attempting to push to Heroku via actions. 

```
2021-01-30T20:37:08.2172789Z HEAD is now at 682a271 Update main.yml
2021-01-30T20:37:08.2445258Z ##[group]Run akhileshns/heroku-deploy@master
2021-01-30T20:37:08.2445970Z with:
2021-01-30T20:37:08.2446424Z   heroku_app_name: dear-genie-dev
2021-01-30T20:37:08.2446886Z   justlogin: true
2021-01-30T20:37:08.2447258Z   branch: HEAD
2021-01-30T20:37:08.2447663Z   dontuseforce: false
2021-01-30T20:37:08.2448077Z   usedocker: false
2021-01-30T20:37:08.2448538Z   docker_heroku_process_type: web
2021-01-30T20:37:08.2448946Z   delay: 0
2021-01-30T20:37:08.2449505Z   rollbackonhealthcheckfailed: false
2021-01-30T20:37:08.2450074Z ##[endgroup]
2021-01-30T20:37:08.6149010Z Created and wrote to ~/.netrc
2021-01-30T20:37:13.5794461Z  ›   Warning: Our terms of service have changed: 
2021-01-30T20:37:13.5797117Z  ›   https://dashboard.heroku.com/terms-of-service
2021-01-30T20:37:13.5847383Z heroku: Press any key to open up the browser to login or q to exit: 
2021-01-30T20:37:13.5920149Z ##[group]Run git config user.name "huong" && git config user.email "huong@huong.com"
2021-01-30T20:37:13.5921076Z [36;1mgit config user.name "huong" && git config user.email "huong@huong.com"[0m
2021-01-30T20:37:13.5922135Z [36;1mgit remote add heroku-dev git@heroku.com:dear-genie-dev.git[0m
2021-01-30T20:37:13.5922870Z [36;1mgit push heroku-dev HEAD:master[0m
2021-01-30T20:37:13.5965568Z shell: /bin/bash -e {0}
2021-01-30T20:37:13.5965901Z ##[endgroup]
2021-01-30T20:37:13.9973110Z Host key verification failed.
2021-01-30T20:37:13.9977901Z fatal: Could not read from remote repository.
2021-01-30T20:37:13.9982196Z 
2021-01-30T20:37:13.9982785Z Please make sure you have the correct access rights
```

My main.yml for the build was: 
```
name: CI

on: 
  push:
    branches:    
      - master 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - name: "Checkout branch"
      uses: actions/checkout@v1
    - name: npm install
      run: |
        npm install
    - name: "Run unit tests"
      run: |
        npm test 
      env:
        CI: true
    - uses: akhileshns/heroku-deploy@master # This is the action we are importing
      with: # It accepts some arguments to work, we can pass the argument using `with`
        heroku_api_key: ${{secrets.HEROKU_API_KEY}} # This is the same as the auth key we generated earlier
        heroku_app_name: "dear-genie-dev" #Must be unique in Heroku
        heroku_email: ${{secrets.EMAIL}} # Email attached to the account
        justlogin: true
    - run: |
        git config user.name "huong" && git config user.email "huong@huong.com"
        git remote add heroku-dev git@heroku.com:dear-genie-dev.git
        git push heroku-dev origin:master
```

I did re-authorize GitHub with heroku and refreshed the Heroku API key, but that didn't solve the problem. Thoughts?

**Comment by madhums** [comment]
Having the same issue! Seems like connecting to github via heroku deploy tab is much easier than this action.

**Comment by old-square-eyes** [comment]
Um - I'm actually having this issue with the deploy tab / connection to Github too!

As least I think I am. I have forked this repo and using Manual Connected deploys, been unable to deploy the dev branch.

After a bit of Googling I found this issue and then noticed that Master is ahead of Dev by one commit.

![image](https://user-images.githubusercontent.com/25760491/133361663-8277039d-72e9-442b-bdfa-b68cdb6f43b6.png)

Here are my symptoms...

https://stackoverflow.com/questions/69172299/heroku-manual-deploy-keeps-switching-to-master?noredirect=1#comment122277072_69172299

**Comment by Spiderpig86** [comment]
I've been running into this issue quite a bit for the past hour:

```
Created and wrote to ~/.netrc
 ›   Warning: Our terms of service have changed: 
Successfully logged into heroku
 ›   dashboard.heroku.com/terms-of-service
heroku: Press any key to open up the browser to login or q to exit:  ›   Warning: heroku update available from 7.47.4 to 7.47.6.
Added git remote heroku
heroku: Press any key to open up the browser to login or q to exit: fatal: 'heroku' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

            Unable to push branch because the branch is behind the deployed branch. Using --force to deploy branch. 
            (If you want to avoid this, set dontuseforce to 1 in with: of .github/workflows/action.yml. 
            Specifically, the error was: Error: Command failed: git push heroku HEAD:refs/heads/master 
fatal: 'heroku' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

        
fatal: 'heroku' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Error: Error: Command failed: git push heroku HEAD:refs/heads/master --force
fatal: 'heroku' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

One possible cause is that `HEROKU_API_KEY` may not be defined in the environment for the Github Action step. As a result, the action would prompt you to log in via a browser.

To resolve, you need to:

- (Optional) Run `heroku auth:token` to generate a new long-term token if you don't have one already.

- Add `HEROKU_API_KEY` to your job's environment.

```yaml
    deploy:
        runs-on: ubuntu-latest
        env:
            HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.4
              
            - name: Deploy to Heroku
              uses: akhileshns/heroku-deploy@v3.12.12
              with:
                  heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
                  heroku_app_name: ${{ secrets.HEROKU_APP }}
                  heroku_email: ${{ secrets.EMAIL }}
```

Hope this helps. 🚀

**Comment by 1xo2** [comment]
i am having the same issue... 
i need help.

Run akhileshns/heroku-deploy@v3.12.12
Created and wrote to ~/.netrc
 ›   Warning: Our terms of service have changed: 
 ›   https://dashboard.heroku.com/terms-of-service
WARNING! Your password will be stored unencrypted in /home/runner/.docker/config.json.
Successfully logged into heroku
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Added git remote heroku
 ▸    Error: Requires exactly one target process type, or --recursive option

            Unable to push branch because the branch is behind the deployed branch. Using --force to deploy branch. 
            (If you want to avoid this, set dontuseforce to 1 in with: of .github/workflows/action.yml. 
            Specifically, the error was: Error: Command failed: heroku container:push web --app shopping-cart-6-cd --arg NODE_ENV                        ="undefined",NEXT_PUBLIC_DATABASE_CONNECTION="${NEXT_PUBLIC_DATABASE_CONNECTION}",NEXT_PUBLIC_JWT_TOKEN_SECRET="${NEXT_PUBLIC_JWT_TOKEN_SECRET}",NEXT_PUBLIC_PAYPAL_CLIENT_ID="${NEXT_PUBLIC_PAYPAL_CLIENT_ID}",NEXT_PUBLIC_PAYPAL_SECRET="${NEXT_PUBLIC_PAYPAL_SECRET}",NEXT_PUBLIC_CLOUDINARY_NAME="${NEXT_PUBLIC_CLOUDINARY_NAME}",NEXT_PUBLIC_API_KEY="${NEXT_PUBLIC_API_KEY}",NEXT_PUBLIC_API_SECRET="${NEXT_PUBLIC_API_SECRET}",NEXT_PUBLIC_GOOGLE_MAP_API="${NEXT_PUBLIC_GOOGLE_MAP_API}"
 ▸    Error: Requires exactly one target process type, or --recursive option

        
 ▸    Error: Requires exactly one target process type, or --recursive option
Error: Error: Command failed: heroku container:push web --app shopping-cart-6-cd --arg NODE_ENV                        ="undefined",NEXT_PUBLIC_DATABASE_CONNECTION="${NEXT_PUBLIC_DATABASE_CONNECTION}",NEXT_PUBLIC_JWT_TOKEN_SECRET="${NEXT_PUBLIC_JWT_TOKEN_SECRET}",NEXT_PUBLIC_PAYPAL_CLIENT_ID="${NEXT_PUBLIC_PAYPAL_CLIENT_ID}",NEXT_PUBLIC_PAYPAL_SECRET="${NEXT_PUBLIC_PAYPAL_SECRET}",NEXT_PUBLIC_CLOUDINARY_NAME="${NEXT_PUBLIC_CLOUDINARY_NAME}",NEXT_PUBLIC_API_KEY="${NEXT_PUBLIC_API_KEY}",NEXT_PUBLIC_API_SECRET="${NEXT_PUBLIC_API_SECRET}",NEXT_PUBLIC_GOOGLE_MAP_API="${NEXT_PUBLIC_GOOGLE_MAP_API}"
 ▸    Error: Requires exactly one target process type, or --recursive option

**Comment by robertherber** [comment]
I'm facing this error now. Works when running the same code locally. Didn't upgrade the action or anything - it just stopped working (and didn't help upgrading to the latest). Seems like there are some outdated underlying dependencies - could that have something to do with it?

<img width="1034" alt="Screenshot 2022-04-07 at 00 05 48" src="https://user-images.githubusercontent.com/1467411/162080026-9440329a-5933-4991-8e6f-b8dd3b45d98a.png">

**Comment by christophby** [comment]
@robertherber same here

**Comment by paintoshi** [comment]
I had a special kind of issue with the AkhileshNS/heroku-deploy. Tried to use a different branch using the branch option but it couldn't find the refs something. Turned out I must checkout the correct branch too when doing that (obviously). It's not in their documentation. See #IMPORTANT.

```
on:
  push:
    branches:
      - special-branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: special-branch # IMPORTANT
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          branch: "special-branch" # IMPORTANT
```
